#name: Github actions demo
#on:
#  push:
#    branches:
#      - '**'
#
#jobs:
#  test-ci:
#    name: Test CI
#    timeout-minutes: 30
#    runs-on: ubuntu-latest
#    permissions:
#      contents: "read"
#      id-token: "write"
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#
#      - name: Set up Maven
#        run: sudo apt-get install -y maven
#
#      - name: Install Chrome
#        run: |
#          sudo apt-get update
#          sudo apt-get --only-upgrade install google-chrome-stable
#
#      - name: CI test
#        run: |
#          mvn clean test -Dtest=com.LoginTest
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: testng-report-${{ github.run_number }}
#          path: |
#            target/surefire-reports/emailable-report.html
name: LambdaTest GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        run: sudo apt-get install -y maven
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
        

      - name: Run Selenium Tests on LambdaTest
        env:
            LT_USERNAME: 'linhbap2911'
            LT_ACCESS_KEY: 'XgH3dlUR8AtaRl3VjzYeG64L2fPAvcDk2hV8XcGb5Nh2VFFKZw'
        run: |
            mvn clean test -Dtest=com.SigninTest
      - uses: actions/upload-artifact@v3
        with:
          name: testng-report-${{ github.run_number }}
          path: |
            target/surefire-reports/emailable-report.html